"""“Secondcommit”

Revision ID: aaa6364768cd
Revises: da7d7e391b62
Create Date: 2023-06-08 15:21:06.104433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa6364768cd'
down_revision = 'da7d7e391b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
