"""Change Vector to Float

Revision ID: 0da4b7fcfe3e
Revises: 3644f6b89f16
Create Date: 2023-02-27 00:50:05.067240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da4b7fcfe3e'
down_revision = '3644f6b89f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
