"""initial_test

Revision ID: b4767af4bf6a
Revises: 155860763b78
Create Date: 2023-02-23 20:42:03.360145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4767af4bf6a'
down_revision = '155860763b78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'path_storage')
    op.drop_column('users', 'face_embeding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_embeding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('path_storage', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
