"""to integer_2

Revision ID: ca7d8bb1978a
Revises: ae4f1ea9f607
Create Date: 2023-02-27 19:25:01.873699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7d8bb1978a'
down_revision = 'ae4f1ea9f607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
